services:
  db:
    image: mysql:8.0
    container_name: library-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - booknest-network

  redis:
    image: redis:alpine
    container_name: library-redis
    ports:
      - "6379:6379"
    command: redis-server --notify-keyspace-events Ex
    volumes:
      - redis_data:/data
    networks:
      - booknest-network

volumes:
  mysql_data:
  redis_data:

networks:
  booknest-network:
    driver: bridge