spring:
  application:
    name: Library-Management-System

  datasource:
    url: jdbc:mysql://localhost:3306/library_management
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        query:
          fail_on_pagination_over_collection_fetch: true

google:
  books:
    api-key: ${GOOGLE_BOOKS_API_KEY}
    base-url: https://www.googleapis.com/books/v1/volumes