spring:
  application:
    name: Library-Management-System

  datasource:
    url: jdbc:${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        query:
          fail_on_pagination_over_collection_fetch: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  data:
    redis:
      url: ${REDIS_URL}


google:
  books:
    api-key: ${GOOGLE_BOOKS_API_KEY}
    base-url: https://www.googleapis.com/books/v1/volumes

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: 108000000

sepay:
  api-url: "https://pay-sandbox.sepay.vn"
  merchant-id: ${SEPAY_MERCHANT_ID}
  secret-key: ${SEPAY_SECRET_KEY}
  return-url: "http://localhost:5173/dashboard/loans"
  cancel-url: "http://localhost:5173/dashboard/loans"
  webhook-token: ${SEPAY_WEBHOOK_TOKEN}
  bank-code: ${SEPAY_BANK_CODE:TCB}
  bank-account: ${SEPAY_BANK_ACCOUNT:93767}

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.hibernate.SQL: WARN
